### ISSUE TITLE
你好，请问为什么按下搜索会调用2次接口？

### ISSUE THREAD

**Issue by zhangxing186176** [LsyWeb/chatgpt-web#3]
![微信图片_20230423161427](https://user-images.githubusercontent.com/130450333/233828182-f0847217-6d36-47d6-8f2d-16b3af1833a4.png)

**Comment by LsyWeb** [comment]
我这边复现不出来，请提供完整操作流程

**Comment by LsyWeb** [comment]
浏览器必须先使用OPTIONS请求进行一个预检请求（preflight request）来获取B服务是否允许跨域请求，服务进行确认之后，才会发起真正的HTTP请求
