### ISSUE TITLE
出错了：TypeError: Cannot read properties of undefined (reading 'data')，请重试

### ISSUE THREAD

**Issue by charlesouwen** [LsyWeb/chatgpt-web#6]
出错了：TypeError: Cannot read properties of undefined (reading 'data')，请重试

**Comment by LsyWeb** [comment]
> 出错了：TypeError: Cannot read properties of undefined (reading 'data')，请重试

本地跑一下，检查一下网络请求返回的结果是否正确，检查一下 airCode 中的云函数运行是否正常
