### ISSUE TITLE
vercel跨域问题

### ISSUE THREAD

**Issue by surkaa** [LsyWeb/chatgpt-web#7]
请问这个项目怎么做到的
在请求后端的时候, 没有发送跨域问题, 
我被这个问题困扰了许久, 
正常的项目解决跨域都能访问到后端, 
而部署到vercel就会发生跨域问题,
如果你方便的话, 能告诉我解决这个问题的关键吗

**Comment by LsyWeb** [comment]
> 请问这个项目怎么做到的 在请求后端的时候, 没有发送跨域问题, 我被这个问题困扰了许久, 正常的项目解决跨域都能访问到后端, 而部署到vercel就会发生跨域问题, 如果你方便的话, 能告诉我解决这个问题的关键吗

这个项目的后端服务是使用的“云函数”，“云函数”的服务里自动配置了允许跨域访问，我猜测你的后端服务没有开启“跨域访问”（CORS），可以检查一下。如果后端是 node 服务，可以使用 [cors](https://www.npmjs.com/package/cors) 这个库进行跨域配置，希望能帮到你

**Comment by surkaa** [comment]
谢谢你的回复, 我现在已经解决这个问题了, 原因是因为我后端服务没有开启 `https` 在https的网站发起http请求, 浏览器是不允许的, 我现在将后端服务配置了 `https` 这个问题就解决了. 再次感谢你的回答
